[package]
authors = ["Mickaël RAYBAUD-ROIG <raybaudroigm@gmail.com>"]
description = "A minimalist static website generator"
include = ["Cargo.toml", "Cargo.lock", "LICENSE.markdown", "README.markdown", "CHANGELOG.markdown", "src/**/.rs", "src/**/.hbs", "example_data/**"]
keywords = ["staticsite", "website", "blog"]
license = "AGPL-3.0"
name = "helianto"
readme = "README.markdown"
repository = "https://github.com/m-r-r/helianto.git"
version = "0.1.0-beta1"

[dependencies]
chrono = "0.2.21"
getopts = "0.2.14"
handlebars = "0.16.0"
log = "0.3.6"
num = "0.1.31"
pulldown-cmark = "0.0.7"
regex = "0.1.61"
rustc-serialize = "0.3.18"
stdio_logger = "0.1.1"
toml = "0.1.28"
walkdir = "0.1.5"
