[package]
authors = ["Mickaël RAYBAUD-ROIG <raybaudroigm@gmail.com>"]
description = "A minimalist static website generator"
include = ["LICENSE.markdown", "src/**/*.rs", "src/templates/*.hbs", "example_data/css/*.css", "example_data/example.markdown"]
keywords = ["static site", "website", "blog"]
license = "AGPL-3.0"
name = "helianto"
readme = "README.markdown"
repository = "https://github.com/m-r-r/helianto.git"
version = "0.1.0-alpha1"

[dependencies]
chrono = "0.2.16"
getopts = "0.2.14.*"
handlebars = "0.11.*"
hoedown = "3.0.3"
log = "0.3.*"
num = "0.1.27"
regex = "0.1.41"
rustc-serialize = "*"
toml = "0.1.23"
walkdir = "0.1.*"

[dependencies.stdio_logger]
git = "https://github.com/m-r-r/stdio_logger"
tag = "0.1.0"
optional = false
