[package]
authors = ["Mickaël RAYBAUD-ROIG <raybaudroigm@gmail.com>"]
name = "helianto"
version = "0.1.0"

[dependencies]
chrono = "0.2.16"
getopts = "0.2.14.*"
handlebars = "0.11.*"
hoedown = "3.0.3"
regex = "0.1.41"
rustc-serialize = "*"
toml = "0.1.23"
walkdir = "0.1.*"
