[package]
authors = ["Mickaël RAYBAUD-ROIG <raybaudroigm@gmail.com>"]
name = "helianto"
version = "0.1.0"

[dependencies]
getopts = "0.2.14.*"
handlebars = "0.11.*"
pulldown-cmark = "0.0.*"
rustc-serialize = "*"
walkdir = "0.1.*"
