[package]
authors = ["Mickaël RAYBAUD-ROIG <raybaudroigm@gmail.com>"]
description = "A minimalist static website generator"
include = ["Cargo.toml", "Cargo.lock", "LICENSE.markdown", "src/**/*.rs", "src/templates/*.hbs", "example_data/css/*.css", "example_data/example.markdown"]
keywords = ["static site", "website", "blog"]
license = "AGPL-3.0"
name = "helianto"
readme = "README.markdown"
repository = "https://github.com/m-r-r/helianto.git"
version = "0.1.0-alpha1"

[dependencies]
chrono = "0.2.16"
getopts = "0.2.14"
handlebars = "0.12.1"
hoedown = "3.0.3"
log = "0.3.4"
num = "0.1.29"
regex = "0.1.44"
rustc-serialize = "0.3.16"
stdio_logger = "0.1.1"
toml = "0.1.23"
walkdir = "0.1.5"
